config/routes.rb
Rails.application.routes.draw do
  get "/bookings", to: "bookings#index"
  post "/bookings/book", to: "bookings#book"
  post "/bookings/release", to: "bookings#release"

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  devise_scope :user do
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  get "/login", to: "home#login"

  post "/slack/command", to: "slack/commands#create"
  root to: "bookings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  protected

  def after_sign_in_path_for(resource)
    bookings_url
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :parking_spot
  scope :for_today, -> { where("created_at >= ? AND created_at < ?", Date.today, Date.tomorrow) }
  scope :not_released, -> { where(released_at: nil) }

  def self.last_user
    User.find(Booking.last.user_id) unless Booking.count == 0
  end

  def release!
    touch(:released_at)
  end

  def released?
    !!released_at
  end
end

app/models/parking_spot.rb
class ParkingSpot < ApplicationRecord
  def self.available?
    Booking.for_today.not_released.empty?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable

  devise :rememberable, :omniauthable, omniauth_providers: %i[slack]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def book_spot
    return unless ParkingSpot.available?

    Booking.create(user_id: id,
      parking_spot_id: ParkingSpot.first.id)
  end

  def release_spot
    last_booking = Booking.last
    return unless Booking.last_user == self && !last_booking.released?

    last_booking.release!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  # GET /bookings or /bookings.json
  def index
    redirect_to login_url unless user_signed_in?

    @spot = ParkingSpot.first
    @spot_owner = Booking.last_user
    @user = current_user
    @bookings = Booking.all
  end

  def book
    current_user&.book_spot
    redirect_back_or_to root_path, notice: (I18n.t "book.success")
  end

  def release
    current_user&.release_spot
    redirect_back_or_to root_path, notice: (I18n.t "release.success")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:user_id, :parking_spot_id, :expires_at, :released_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
    redirect_to bookings_url if user_signed_in?
  end
end

app/controllers/slack/commands_controller.rb
class Slack::CommandsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :verify_slack_request

  def create
    message = case params[:text].downcase
    when "book" then book
    when "release" then release
    when "who" then parking_spot_owner
    else
      I18n.t "invalid_command"
    end

    render json: {text: message}
  end

  private

  def verify_slack_request
    # make sure request is coming from Slack
  end

  def book
    if current_user.book_spot
      I18n.t "book.success"
    else
      I18n.t "book.failure"
    end
  end

  def release
    if current_user.release_spot
      I18n.t "release.success"
    else
      I18n.t "release.failure"
    end
  end

  def parking_spot_owner
    if ParkingSpot.available?
      I18n.t "who.none"
    elsif Booking.last_user == current_user
      I18n.t "who.you"
    else
      I18n.t "who.someone", user: Booking.last_user.name
    end
  end

  def current_user
    uid = params[:user_id] + "-" + params[:team_id]
    user = User.find_by(uid: uid)
    return user unless user.nil?

    User.create(name: params[:user_name], uid: uid, provider: "slack")
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :slack

  def slack
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Slack") if is_navigational_format?
    else
      session["devise.slack_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
  <strong>Booking #<%= booking.id %>:</strong>
    <%= User.find(booking.user_id).name.capitalize + " booked the parking spot at " %>
    <%= booking.created_at %>
    <% if booking.released_at %>
      <%= "and released it at: #{booking.released_at}" %>
    <% end %>
  </p>
</div>

app/views/bookings/index.html.erb
<h2>
  At this moment, the parking spot is: 
  <% if ParkingSpot.available? %>
    <%= " Available" %></h2>
    <div><%= button_to "Book Parking Spot", bookings_book_url %></div>
  <% elsif @spot_owner == @user %>
    <%= " Booked (by you)" %></h2>
  <div><%= button_to "Release Parking Spot", bookings_release_url %></div>
  <% else %>
    <%= " Booked (by #{@spot_owner.name})" %></h2>
  <% end %>

<strong>Booking History</strong>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
  <% end %>
</div>

<div>
  <%= button_to "Sign Out", destroy_user_session_url, method: :delete %>
</div>

app/views/home/login.html.erb
<p>In order to use Parking App, please log in using your Slack account.</p>

<p><%= button_to "Sign in with Slack", user_slack_omniauth_authorize_path, data: { turbo: false }  %><p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color: green"><%= notice %></p>
    <p style="color: red"><%= alert %></p>
    <%= yield %>
  </body>
</html>